### ISSUE TITLE
Anyway to cancel and save proxies?

### ISSUE THREAD

**Issue by Milor123** [monosans/proxy-scraper-checker#316]
Hey bro! I am using docker, but I would like know can cancel or save the progress while the script is scrapping

Like scrapebox that it save a txt while found the urls that works with the "check_website"
But it takes loooongs times and when i press control+C then I lost all. Or am I doing wrong?

tom file:
```
# The number of seconds to wait for a proxied request.
# The higher the number, the longer the check will take
# and the more proxies you get.
timeout = 7

# The number of seconds to wait for the proxies to be downloaded from the source.
source_timeout = 15

# Maximum concurrent connections.
# Don't be in a hurry to set high values.
# Make sure you have enough RAM first, gradually increasing the default value.
# If set to 0, the maximum value available for your OS will be used.
max_connections = 200

# URL to which to send a request to check the proxy.
# If it is not httpbin or a service that returns an IP address,
# it will be impossible to determine the anonymity and geolocation of the proxy.
# Example:
# check_website = "https://google.com"
# check_website = "https://httpbin.smp.io/ip"
check_website = "https://google.com"

# Set to false to sort proxies alphabetically.
sort_by_speed = true

# Save the geolocation of the proxy exit-node.
# Uses offline geolocation database.
# Only works for json output.
enable_geolocation = false

# Enable output of all errors. Significantly slows down proxy checking.
debug = false

[output]
# Path to the folder where the proxies will be saved.
# Leave blank to save the proxies to the current directory.
# This option is ignored in Docker.
path = "/home/app/.local/share/proxy_scraper_checker"
```

compose file (I've changed the map line to `/home/app/.local/share/proxy_scraper_checker`)
```
services:
  app:
    image: proxy_scraper_checker
    build:
      context: .
      args:
        - GID=${GID:-1000}
        - UID=${UID:-1000}
    tty: true
    volumes:
      - proxy_scraper_checker_cache:/home/app/.cache/proxy_scraper_checker
      - ./out:/home/app/.local/share/proxy_scraper_checker
      - ./config.toml:/app/config.toml
volumes:
  proxy_scraper_checker_cache:

```
